config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :chats
  root 'posts#index'

  resources :posts, except: [:index] do
    resources :comments, shallow: true do
      resources :replies
    end
    resources :votes, only: %i[index create]
    delete 'votes', to: 'votes#destroy'
    post 'seen', to: 'posts#mark_as_seen'
  end

  resources :users, only: %i[index show] do
    # follows
    resource :follows, only: %i[create destroy]
    get 'followings', to: 'follows#following'
    get 'followers', to: 'follows#follower'

  end

  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_up: 'register',
    sign_out: 'logout'
  }, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }
end

app/models/follow.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: follows
#
#  id          :integer          not null, primary key
#  follower_id :integer          not null
#  followed_id :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  counter_culture :follower, column_name: "followings_count", touch: true
  counter_culture :followed, column_name: "followers_count", touch: true

  validates :followed_id, :follower_id, presence: true
  # User should not follow himself/herself
  validates :follower_id, comparison: { other_than: :followed_id }
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  first_name             :string           not null
#  last_name              :string
#  username               :string
#  birthdate              :date             not null
#  gender                 :integer          not null
#  country                :string           not null
#  hometown               :string
#  current_city           :string
#  last_seen_at           :datetime
#  biography              :string
#  followings_count       :integer          default(0), not null
#  followers_count        :integer          default(0), not null
#  posts_count            :integer          default(0), not null
#  comments_count         :integer          default(0), not null
#  blocked_users_count    :integer          default(0), not null
#  verified               :boolean          default(FALSE), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#
class User < ApplicationRecord
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Associations
  with_options dependent: :destroy do |association|
    association.has_many :active_friendships, class_name: "Follow", foreign_key: :follower_id
    association.has_many :passive_friendships, class_name: "Follow", foreign_key: :followed_id
    association.has_many :posts, -> { order(id: :desc) }
    association.has_one_attached :profile
    association.has_one_attached :cover_picture
  end

  ### I don't want to destroy
  # has_many :seen_posts
  has_many :chat_rooms
  has_many :chat_room_users, through: :chat_rooms
  has_many :messages

  has_many :followings, through: :active_friendships, source: :followed
  has_many :followers, through: :passive_friendships, source: :follower

  acts_as_voter

  include UserConcern

  ## Scopes
  scope :not_following, ->(limit = 20, exclude_ids) do
          with_attached_profile.where.not(id: exclude_ids).limit(limit)
        end

  scope :male, -> { where(gender: User::GENDER[:male]) }
  scope :female, -> { where(gender: User::GENDER[:female]) }
end

## validations, callbacks, and methods are in models/concerns/user_concern.rb
## This file includes only [scopes and associations]

app/controllers/follows_controller.rb
# frozen_string_literal: true

class FollowsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user, only: %i[create destroy following follower]

  # POST /users/:user_id/follows
  def create
    current_user.follow @user
    render_partial_user
  end

  # DELETE /users/:user_id/follows
  def destroy
    current_user.unfollow @user
    render_partial_user
  end

  # GET /users/:user_id/followings
  def following
  end

  # GET /users/:user_id/followers
  def follower
    @users = @user.followers.limit(50)
  end

  ## private
  def find_user
    @user = User.find(params[:user_id])
  end

  def render_partial_user
    locals = { user: @user, follows: (action_name == "create") }
    render partial: "follows/follow", locals: locals
  end
end

app/views/follows/_follow.html.erb
<% if follows %>
  <% btn_class = 'focus:cursor-wait focus:disabled inline-block w-28 text-center font-semibold py-1 rounded-xl bg-following text-white' %>
  <% btn_name = 'Following' %>
  <% request_type = :delete %>
<% else %>
  <% btn_class = 'focus:cursor-wait focus:disabled hover:cursor-pointer w-28 text-center font-semibold py-1 rounded-xl bg-btn text-white' %>
  <% btn_name = 'Follow' %>
  <% request_type = :post %>
<% end %>

<%= turbo_frame_tag "#{dom_id(user)}-follow" do %>
  <%= button_to btn_name, user_follows_path(user), class: btn_class, method: request_type %>
<% end  %>

app/views/follows/follower.html.erb
<div class="root sm:w-full xl:w-desktop bg-gray-100 h-full w-70 m-auto">
  <div class="bg-white h-full overflow-y-scroll divide-y divide-gray-10" data-controller="user">
    <i class="m-2 bx bxs-left-arrow-circle bx-sm text-tint" data-action="click->user#redirectBack"></i>
    <%= render @users %>
  </div>
</div>

app/views/follows/following.html.erb
<div class="sm:w-full xl:w-desktop bg-gray-100 h-full w-70 m-auto">
  <div class="bg-white w-full h-full overflow-y-scroll divide-y divide-gray-10" data-controller="user">
    <div class="h-8 p-2 top-0 w-full flex items-center justify-between" data-controller="application">
      <i class="bx bxs-left-arrow-circle bx-sm text-tint" data-action="click->application#redirectBack"></i>
      <% if @users.ids.count == 30 %>
        <%= link_to '', followings_user_path(@user, page: (@page + 1)), class: 'text-tint bx bxs-right-arrow-circle'%>
      <% end %>
    </div>

    <% if @follows %>
      <%= render @users, { user: @user, follows: @follows, f_path: true } %>
    <% else %>
      <% @users.each do |user| %>
        <% follows = @following_ids.include? user.id %>
        <%= render user, { user: user, follows: follows, f_path: true } %>
      <% end %>
    <% end %>
  </div>
</div>